reviewer_journals:
  - name: "Computer Networks"
    link: "https://www.sciencedirect.com/journal/computer-networks"
    publisher: "Elsevier"
  - name: "Transactions on Emerging Telecommunications Technologies"
    link: "https://onlinelibrary.wiley.com/journal/21613915"
    publisher: "Wiley"
  - name: "Internet Technology Letters"
    link: "https://onlinelibrary.wiley.com/journal/24761508"
    publisher: "Wiley"
  - name: "Pervasive and Mobile Computing"
    link: "https://www.sciencedirect.com/journal/pervasive-and-mobile-computing"
    publisher: "Elsevier"
  - name: "Journal of Information Assurance and Security (JIAS)"
    link: "https://sciendo.com/pl/journal/IAS"
    publisher: "Cerebration Science Publishing"
  - name: "IoT"
    link: "https://www.mdpi.com/journal/IoT"
    publisher: "MDPI"
  - name: "Electronics"
    link: "https://www.mdpi.com/journal/electronics"
    publisher: "MDPI"
  - name: "Symmetry"
    link: "https://www.mdpi.com/journal/symmetry"
    publisher: "MDPI"

reviewer_conferences:
  - name: "WiMob - '20"
    link: "http://www.wimob.org/wimob2024/"

teaching_assistant:
  - course: "Advanced coding tools and methodologies"
    university: "Politecnico di Milano"

lecturer:
  - course: "Probability and Statistics for Computer Science"
    university: "University of Insubria"

guest_lectures:
  - name: "AI and Cyber-security."
    venue: "Bachelors degree course on Legal Computer Science"
    institution: "University of Insubria"
    date: "Nov 2023"
  - name: "AI: working principles, advantages and disadvantages."
    venue: "Bachelors degree course on Legal Computer Science"
    institution: "University of Insubria"
    date: "Nov 2024"

projects:
  - role: "Member"
    institution: "Insubria University"
    name: “SERENA-IIoT” 
    description: "SEcure and REliable Networked Architecture for Industrial Internet of Things digital transformationg"
    funding: "financed by MUR (Ministero dell’Università e della Ricerca) and by European Union (Next Generation EU), PRIN 2022 (project code 2022CN4EBH)"
    link: "https://serenaiiot.dista.uninsubria.it/"

thesis_advisor:
  - title:
    author:
    year:
    role: "Advisor"